#!/usr/bin/env python
# -*- coding:utf8 -*-


# dc ={'c':1,'b':3,'d':2,'a':5}
# dc = sorted(dc.items())
# print(dc)

# a=10
# b=0
# try:
#     c=a/b
#     print(c)
# except Exception as e:
#     print(e)
# else:
#     print('no error')
#
# print("done")
#
# print(type(1))
#
# try:
#      s = None
#      if s is None:
#          print ("s 是空对象")
#          raise NameError     #如果引发NameError异常，后面的代码将不能执行
#      print (len(s))  #这句不会执行，但是后面的except还是会走到
# except NameError:
#      print ("空对象没有长度")





